export const characters: string[] = [
  "A suspiciously normal guy",
  "A glowing-eyed teenager",
  "An exhausted old wizard",
  "A child who speaks to shadows",
  "A cloaked wanderer",
  "A person made of glass",
  "A being with shifting faces",
  "A masked figure with no reflection",
  "A person covered in runes",
  "A body stitched from multiple souls",
  "A mushroom creature",
  "A winged elf",
  "A half-dragon",
  "A cursed knight",
  "A goblin with a golden tooth",
  "A centaur",
  "A mermaid with mechanical fins",
  "A banshee",
  "A shadowy fae",
  "A living spell",
  "A sentient vending machine",
  "A cyborg",
  "A rogue AI",
  "A humanoid robot",
  "A clone",
  "An alien child",
  "A crystal android",
  "A mech made from bones",
  "A glitching hologram",
  "A synthetic lifeform",
  "A raccoon in a trench coat",
  "A talking cat",
  "A psychic goldfish",
  "A crow with glowing eyes",
  "A battle-scarred toad",
  "A three-headed dog",
  "A llama with spiral pupils",
  "A sloth with ancient markings",
  "A chameleon that flickers like fire",
  "A fox with nine tails",
  "A ghost",
  "A fire spirit",
  "A vampire",
  "A genie",
  "A talking skeleton",
  "A siren",
  "A demon",
  "A shapeshifter",
  "A living curse",
  "A will-o'-the-wisp",
  "A floating cloud with eyes",
  "A walking mirror",
  "A trench coat full of smoke",
  "A sentient shadow",
  "A ball of yarn with eyes",
  "A disembodied smile",
  "A glitch in reality",
  "A swarm of butterflies acting as one being",
  "A humanoid made of clockwork",
  "A thought made flesh",
  "A nervous middle manager",
  "A bored office intern",
  "A man in his pajamas",
  "A barista who never blinks",
  "A librarian who remembers too much",
  "A retiree who glows slightly",
  "A dog in a hoodie",
  "A sleep-deprived student",
  "A cashier who speaks in rhyme",
  "A grandma who levitates slightly",
  "A janitor with glowing eyes",
  "A fluffy penguin",
];

export const descriptors: string[] = [
  "glowing-eyed",
  "shadowy",
  "ancient",
  "mischievous",
  "bioluminescent",
  "partially transparent",
  "covered in moss",
  "levitating slightly",
  "surrounded by a faint mist",
  "cracked but still alive",
  "dripping with stardust",
  "stitched together",
  "made of vines",
  "radiating warmth",
  "constantly flickering",
  "weeping silently",
  "wrapped in chains",
  "glitching between dimensions",
  "with eyes that shift color",
  "bearing strange symbols",
  "hovering just above the ground",
  "smoking at the edges",
  "trailing flower petals",
  "with feathers instead of hair",
  "with an aura of static",
  "buzzing with electricity",
  "made of polished stone",
  "formed from shifting shadows",
  "with cracks leaking light",
  "dripping with ink",
  "with a mirrored face",
  "carved from ice",
  "carved from wood",
  "smelling faintly of lavender",
  "held together by light",
  "driven by unknowable logic",
  "with stars in their eyes",
  "constantly twitching",
  "soft and glowing",
  "strangely symmetrical",
  "glowing from within",
  "made of paper and string",
  "with no visible mouth",
  "flickering like a candle",
  "painted in dreamlike colors",
  "always watching",
  "vaguely unsettling",
  "humming quietly",
  "bathed in moonlight",
  "wrapped in old cloth",
  "silently screaming",
  "glimmering like crystal",
  "mildly annoyed",
  "perpetually confused",
  "unusually calm",
  "wearing far too many scarves",
  "extremely average",
  "suspiciously clean",
  "weirdly symmetrical",
  "still wearing pajamas",
  "visibly over-caffeinated",
  "drenched in office lighting",
  "covered in glitter accidentally",
  "with post-it notes stuck to their back",
  "leaking coffee",
  "vibrating from stress",
  "wearing socks that do not match",
  "with a faint smell of burnt toast",
  "made of an oozy, gooey substance",
];

export const roles: string[] = [
  "a wanderer",
  "an oracle",
  "a guardian",
  "a collector of forbidden relics",
  "a lost heir",
  "a dreamweaver",
  "a storyteller",
  "a fugitive",
  "an artifact hunter",
  "a seer of timelines",
  "a dimension hopper",
  "a beast tamer",
  "a time traveler",
  "a mirror maker",
  "a cloud herder",
  "a dragon caretaker",
  "a potion brewer",
  "a gatekeeper",
  "a witch in hiding",
  "an escaped experiment",
  "a key bearer",
  "a fortune teller",
  "an illusionist",
  "a ghost whisperer",
  "an artifact forger",
  "a soul stitcher",
  "a shadow puppeteer",
  "a junkyard prophet",
  "a graveyard keeper",
  "a storm chaser",
  "a reality anchor",
  "a dream cartographer",
  "a nightmare hunter",
  "a cursed royal",
  "a memory thief",
  "a dollmaker",
  "a cyber monk",
  "a post-apocalyptic courier",
  "a hologram archivist",
  "a starlight smuggler",
  "a gravity sculptor",
  "an underworld diplomat",
  "a mechanical oracle",
  "a plague survivor",
  "a soul librarian",
  "a cosmic hitchhiker",
  "a ritualist",
  "a data shaman",
  "a void explorer",
  "a relic trader",
  "a ghost train conductor",
  "a mall security guard",
  "a temp agency intern",
  "a school lunch monitor",
  "a parking inspector",
  "a retail employee of the month",
  "a maintenance worker at a haunted hotel",
  "a substitute teacher from another timeline",
  "a coffee shop regular",
  "an office gossip source",
  "a neighborhood wizard",
  "a laundromat attendant",
  "an apartment complex mediator",
  "a underground bingo champion",
  "a frequent flier in dreamspace",
  "a caretaker of forgotten pets",
  "a pigeon negotiator",
  "a library basement resident",
  "a children's toy",
];

export const actions: string[] = [
  // Sci-fi / Surreal
  "guarding a mysterious egg",
  "drifting through a dreamscape",
  "repairing a broken star",
  "hiding from invisible watchers",
  "communing with a ghost",
  "floating inside a protective bubble",
  "talking to a sentient plant",
  "repairing a mechanical bird",
  "opening a glowing book",
  "trapped in a loop of time",
  "pouring stardust into a bottle",
  "conversing with a flickering hologram",
  "stitching a portal shut",
  "harvesting light from fireflies",
  "watching memories flicker on a screen",
  "feeding coins to a talking vending machine",
  "rewriting a map with living ink",
  "igniting a constellation by hand",
  "escaping from a collapsing timeline",
  "translating alien glyphs",
  "watching a city fold in on itself",
  "swimming through solid light",

  // Fantasy / Magical
  "weaving spells into the air",
  "feeding a baby dragon",
  "playing chess with a shadow",
  "singing to forgotten gods",
  "walking through a field of memories",
  "lighting candles that float midair",
  "playing a lullaby to the void",
  "hatching a plan beneath glowing runes",
  "tracing a sigil in the air",
  "knitting with thread made of moonlight",
  "resting beside a sleeping giant",
  "taming a storm",
  "summoning something from a puddle",
  "carving runes into stone with bare hands",
  "riding a glowing stag through the fog",
  "sleeping in a nest of vines and feathers",
  "arguing with a sarcastic mirror",
  "feeding moss to a tiny golem",
  "standing in a ring of toadstools",
  "sharing secrets with a forest spirit",
  "combing the clouds with a giant brush",
  "watching constellations rearrange themselves",
  "trying to escape from inside a book",

  // Mundane / Surreal-Normal
  "drinking coffee in total silence",
  "sweeping an endless floor",
  "waiting for a bus that never comes",
  "watering plastic plants",
  "filing mysterious paperwork",
  "reading a book with no words",
  "typing on a keyboard made of stone",
  "holding an umbrella indoors",
  "arguing with a customer service demon",
  "making toast one slice at a time",
  "taking notes in an invisible notebook",
  "sharpening pencils that scream slightly",
  "changing a lightbulb that won't stop glowing",
  "eating cereal at midnight",
  "carrying a fish tank with no fish",
  "answering a phone that hasn't rung",
  "waiting in line behind statues",
  "ironing an infinite scarf",
  "navigating cubicles in a maze",
  "sleeping under a conference table",
  "refilling the office water cooler with moonlight",
  "surrounded by its children",
];

export const companionsOrProps: string[] = [
  "a sentient umbrella",
  "a sarcastic talking skull",
  "a pet rock that hums softly",
  "a floating lantern with its own agenda",
  "a briefcase that growls when opened",
  "a pocket-sized dragon",
  "an enchanted tea kettle",
  "a violin that plays itself when sad",
  "a goblin in a backpack",
  "a cactus in a coffee mug",
  "a holographic cat that flickers occasionally",
  "a grumpy enchanted book",
  "a baby kraken in a fishbowl",
  "a cracked crystal ball showing random memories",
  "a raven that delivers post-it notes",
  "a mechanical mouse named Click",
  "a floating orb that dispenses riddles",
  "a deflated balloon with a soul",
  "a ghost in a jar",
  "a broom with trust issues",
  "a rubber duck that quacks ominously",
  "a glowing cube that changes color based on mood",
  "a teddy bear with one eye and too many secrets",
  "a coffee thermos with infinite depth",
  "a journal that edits itself",
  "a backpack full of mysterious snacks",
  "a paperclip that gives unsolicited advice",
  "a weather-controlling umbrella",
  "a plant that dances to silence",
  "a pocket watch with a heartbeat",
  "a mirror shard that whispers truths",
  "a scarf that tightens when danger is near",
  "a laptop that types on its own",
  "a flip phone that only calls the past",
  "a tiny golem made of staplers",
  "a suitcase full of wind",
  "a broom that writes poetry",
  "a sock puppet with prophetic visions",
  "a glowing feather that floats behind them",
  "a floating fishbowl orbiting their head",
];

export const settings: string[] = [
  // Fantasy
  "a mountain cave filled with glowing crystals",
  "a haunted forest where the trees whisper secrets",
  "a floating castle above the clouds",
  "a library buried beneath a volcano",
  "a swamp lit by fireflies the size of owls",
  "a forgotten temple deep in the jungle",
  "an enchanted orchard with golden apples",
  "a crumbling fortress surrounded by mist",
  "a snowy village under eternal moonlight",
  "a magical glade with a glowing pond",

  // Sci-Fi
  "a spaceship drifting near a black hole",
  "a lab suspended in zero gravity",
  "a forgotten space station overrun with moss",
  "a virtual city inside a quantum computer",
  "a dome colony on a red planet",
  "a reactor core flooded with neon mist",
  "a cybernetic scrapyard in orbit",
  "a desert where time moves backward",
  "an AI-controlled greenhouse in the void",
  "a stasis pod buried beneath alien sand",

  // Mundane / Surreal Normal
  "an abandoned office lit only by exit signs",
  "a grocery store at 3 a.m.",
  "a laundromat that loops in time",
  "a school hallway that never ends",
  "a public library where the shelves rearrange themselves",
  "a suburban backyard filled with ancient ruins",
  "a train station with no visible trains",
  "a parking garage beneath the ocean",
  "an apartment where gravity flickers",
  "a dentist's office during a thunderstorm",
  "an expansive arctic tundra",

  // Cross-genre / Weird
  "a café between dimensions",
  "a stairwell that leads to different realities",
  "an elevator with infinite buttons",
  "a cathedral made of bone and glass",
  "a marketplace that only appears at dusk",
  "a dream stitched together from strangers' minds",
  "a carnival run by ghosts",
  "a museum of forgotten lives",
  "a skybridge where people speak in riddles",
  "a motel where time stands still",
];

export const environmentalFeatures: string[] = [
  // Fantasy
  "glowing mushrooms sprouting from the walls",
  "floating lanterns bobbing gently in the air",
  "runes pulsing faintly with magic",
  "vines that move when you're not looking",
  "a distant humming from deep underground",
  "an ethereal mist that clings to the floor",
  "bones half-buried in moss",
  "a soft golden glow with no visible source",
  "fairy lights blinking in impossible patterns",
  "a storm of petals swirling slowly in midair",

  // Sci-Fi
  "holograms flickering in and out of existence",
  "surfaces lined with glowing circuit veins",
  "a low mechanical heartbeat echoing in the distance",
  "artificial gravity shifting unpredictably",
  "walls that seem to breathe",
  "liquid light pooling in corners",
  "transparent floor panels revealing stars below",
  "a faint radio signal whispering unintelligibly",
  "drifting debris caught in suspended animation",
  "a soft drone of maintenance bots in the dark",

  // Mundane / Surreal
  "fluorescent lights buzzing inconsistently",
  "a ceiling fan spinning far too slowly",
  "posters peeling off the walls in a breeze that shouldn't exist",
  "static crackling from an old CRT monitor",
  "endless coffee stains on the floor",
  "rows of identical potted plants, all fake",
  "a single flickering lightbulb",
  "elevator music playing from nowhere",
  "mysterious sticky notes everywhere",
  "the smell of burnt toast lingering in the air",

  // Cross-Genre / Weird
  "gravity-defying dust motes floating upward",
  "shadows stretching in the wrong direction",
  "clock hands spinning uncontrollably",
  "echoes that respond before you speak",
  "doors that lead nowhere but still creak open",
  "footprints appearing behind you",
  "a faint glow tracing the edges of everything",
  "the air shimmering like a heatwave",
  "time appearing fractured around the edges",
  "the sound of breathing with no one nearby",
];

export const atmospheres: string[] = [
  // Lighting-based
  "bathed in warm golden light",
  "lit by flickering torchlight",
  "glowing softly from an unknown source",
  "illuminated by bioluminescent plants",
  "shrouded in deep blue twilight",
  "washed in harsh fluorescent light",
  "lit only by the glow of distant stars",
  "dimly lit by pulsing red alerts",
  "glittering under moonlight",
  "cast in long, shifting shadows",

  // Emotional / Mood-based
  "wrapped in a heavy, expectant silence",
  "tense with unspoken danger",
  "calm and dreamlike",
  "eerily peaceful",
  "chaotic but strangely organized",
  "quietly oppressive",
  "buzzing with nervous energy",
  "serene but unsettling",
  "lonely and echoing",
  "charged with arcane energy",

  // Weather / Elemental
  "drifting with gentle snowfall",
  "blanketed in fog",
  "pelted by slow, heavy rain",
  "hazy with floating ash",
  "thick with swirling sand",
  "humid and suffocating",
  "pierced by sudden lightning",
  "bathed in swirling mist",
  "echoing with distant thunder",
  "filled with drifting embers",

  // Surreal / Weird
  "bathed in upside-down sunlight",
  "vibrating softly with unseen tension",
  "flickering in and out of sync with time",
  "painted in greyscale despite color",
  "humming with residual magic",
  "glimmering like a memory",
  "weighed down by a strange gravity",
  "moving in slow motion",
  "bending light around every edge",
  "as if submerged underwater",
];